name = "tensorplay-blog-images"
main = "cloudflare_worker.js"
compatibility_date = "2024-03-20"

# 绑定 R2 Bucket
[[r2_buckets]]
binding = "blog" # 代码中使用的变量名
bucket_name = "blog"    # Cloudflare Dashboard 中的真实 Bucket 名称

# 自定义域名路由（可选，部署后也可以在 Dashboard 配置）
# routes = [
#   { pattern = "image.tensorplay.cn", custom_domain = true }
# ]
